# Generated by Django 5.2.1 on 2025-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
