# Generated by Django 5.2.1 on 2025-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
