# Generated by Django 5.2.1 on 2025-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_joined_date_member_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
